env:
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - always
  no-console: off
globals:
  jasmine: true
  window: true
  fetch: true
  Headers: true
  document: true
  Cookies: true
  nearConfig: true
  nearlib: true
  near: true
  walletAccount: true
  contract: true
  testSettings: true


