language: node_js
node_js:
  - 12
env:
  - NODE_ENV=ci
  - NODE_ENV=ci-betanet
cache: yarn
script:
  - yarn lint
  - yarn test
notifications:
  email:
      recipients:
        - devx@near.org
      on_success: never # default: change
      on_failure: change # default: always
